name: build

on:
  pull_request:
    branches:
      - dev
      - master
  push:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        $CONDA/bin/conda install -c bioconda viennarna -y
        $CONDA/bin/pip install -e .
    - name: Lint
      run: |
        $CONDA/bin/pip install pylint pydocstyle
        $CONDA/bin/pylint --reports=n flexs
        $CONDA/bin/pydocstyle flexs
    - name: Test with pytest
      run: |
        $CONDA/bin/conda install pytest
        $CONDA/bin/pytest tests
